### ISSUE TITLE
Add More Align() Features

### ISSUE THREAD

**Issue by flip4bytes** [corysimmons/flexgrid#16]
The first thing I used the align() function to do was for `justify-content: flex-end` (to right align navigation on the page).

`justify-content` has some pretty powerful settings: `flex-start | flex-end | center | space-between | space-around` - I have used `space-between` before, it's particularly useful when doing a column layout (like header // hero tagline // bottom navigation.)

All of those would be useful to implement really, it feels a little barebones just having it for vertically/horizontally centering content. For now I'll just add in `display: flex` `justify-content: flex-end` in my code.

I guess I'm curious as to what your plans are for feature set and exactly what you want to make flexgrid be at the end of the day. Is it to make flexbox easier and quicker implement? Because in that case, I'd say transfer over most of the spec like `justify-content` for example.

Cheers!

**Comment by corysimmons** [comment]
I'm not really interested in just converting all of Flexbox's code to FlexGrid stuff. `align()` is primarily in there for vertical and horizontal centering and that's going to be it.

In your case, I'd highly suggest just mixing and matching FlexGrid and Flexbox as they work pretty well together.
