### ISSUE TITLE
Fix $flex: true Functionality

### ISSUE THREAD

**Issue by flip4bytes** [corysimmons/flexgrid#6]
Currently $flex: true overwrites the previous constraints set by a fraction e.g. `box(1/4, $flex: true)` will just turn on flex entirely for the column and it will automatically fit as much on one line as possible before moving down to the next line when constraints are met.

I would instead expect the bottom example to happen when `$flex: true` was set:
![](http://i.imgur.com/6glIhlc.jpg)

( [This above example can be found on codepen](http://codepen.io/flip4bytes/pen/gbrJaz))

The `$flex: true` way that you currently have it should be a standalone mixin like `flex()` or something because it is a really important feature. That mixin wouldn't consist of any fraction functionality of course.

I think it's smart to have `box()` always maintain any given proportions though. Just as a box has proportions while flex doesn't, flex is supposed to adapt and respond by itself.

Looking great so far btw!

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/flexgrid/commit/55c48b459b866eb93054cd3c5e5e526fb6bd813d

Let me know if it works for you. I'll reopen if it doesn't.

Works nicely in the demo http://corysimmons.github.io/flexgrid
